 meta_product_name: "Cookbud App"
 meta_title: "Cookbud - Find recipes with ingredients you have at home"
 meta_description: "Welcome to Cookbud - Find your favorite recipes by ingredients, preferences, diets and start cooking like a pro!"
 meta_image: "og_image.jpg"
twitter_account: "@product_twitter_account"
